"""Layout, geometry, padding, and sizing."""

# Window sizing
WINDOW_MIN_WIDTH = 1280
WINDOW_MIN_HEIGHT = 800
SIDEBAR_WIDTH = 180

# Controls sizing
BUTTON_MIN_HEIGHT = 18
BUTTON_MIN_WIDTH = 140
INPUT_HEIGHT = 28
PROGRESSBAR_HEIGHT = 18
SCROLLBAR_WIDTH = 10
SCROLLBAR_RADIUS = 4

# Spacing / padding / radius
PADDING_SMALL = 6
PADDING_MEDIUM = 8
PADDING_LARGE = 12
BORDER_RADIUS_SMALL = 4
BORDER_RADIUS = 6
BORDER_RADIUS_LARGE = 8

# Widget paddings / margins
MENU_BUTTON_PADDING_X = 12
MENU_BUTTON_PADDING_Y = 10
COMBOBOX_PADDING = 6
INPUT_PADDING_Y = PADDING_SMALL
INPUT_PADDING_X = PADDING_SMALL * 2
GROUPBOX_TITLE_MARGIN_TOP = 12
HEADER_SECTION_PADDING = PADDING_SMALL
GROUP_TITLE_PADDING_X = 8
GROUP_TITLE_PADDING_Y = 4

# RAG view sizing
JOB_SELECTOR_WIDTH = 300
CONTEXT_PANEL_WIDTH = 350
CHAT_INPUT_HEIGHT = 80
GUI_CHAT_BUBBLE_MAX_WIDTH = 1800
GUI_CHAT_BUBBLE_MIN_WIDTH = 200

# Cards / widgets
STATS_CARD_MIN_HEIGHT = 100
TABLE_ROW_HEIGHT = INPUT_HEIGHT
TABLE_COLUMN_ID_WIDTH = 250
GUI_FILELIST_MIN_HEIGHT = 100
GUI_DOC_TYPE_EXTRA_WIDTH = 50
GUI_BUTTON_HEIGHT_OFFSET = 4
GUI_PROGRESS_HEIGHT_OFFSET = 4
GUI_DETAIL_PROGRESS_HEIGHT_OFFSET = 8
GUI_CLEAR_BUTTON_SIZE = (60, 20)
GUI_STATUS_INDICATOR_SIZE = None
GUI_STATS_CARD_HEIGHT = 100

__all__ = [
    "WINDOW_MIN_WIDTH",
    "WINDOW_MIN_HEIGHT",
    "SIDEBAR_WIDTH",
    "BUTTON_MIN_HEIGHT",
    "BUTTON_MIN_WIDTH",
    "INPUT_HEIGHT",
    "PROGRESSBAR_HEIGHT",
    "SCROLLBAR_WIDTH",
    "SCROLLBAR_RADIUS",
    "PADDING_SMALL",
    "PADDING_MEDIUM",
    "PADDING_LARGE",
    "BORDER_RADIUS_SMALL",
    "BORDER_RADIUS",
    "BORDER_RADIUS_LARGE",
    "MENU_BUTTON_PADDING_X",
    "MENU_BUTTON_PADDING_Y",
    "COMBOBOX_PADDING",
    "INPUT_PADDING_Y",
    "INPUT_PADDING_X",
    "GROUPBOX_TITLE_MARGIN_TOP",
    "HEADER_SECTION_PADDING",
    "GROUP_TITLE_PADDING_X",
    "GROUP_TITLE_PADDING_Y",
    "JOB_SELECTOR_WIDTH",
    "CONTEXT_PANEL_WIDTH",
    "CHAT_INPUT_HEIGHT",
    "GUI_CHAT_BUBBLE_MAX_WIDTH",
    "GUI_CHAT_BUBBLE_MIN_WIDTH",
    "STATS_CARD_MIN_HEIGHT",
    "TABLE_ROW_HEIGHT",
    "TABLE_COLUMN_ID_WIDTH",
    "GUI_FILELIST_MIN_HEIGHT",
    "GUI_DOC_TYPE_EXTRA_WIDTH",
    "GUI_BUTTON_HEIGHT_OFFSET",
    "GUI_PROGRESS_HEIGHT_OFFSET",
    "GUI_DETAIL_PROGRESS_HEIGHT_OFFSET",
    "GUI_CLEAR_BUTTON_SIZE",
    "GUI_STATUS_INDICATOR_SIZE",
    "GUI_STATS_CARD_HEIGHT",
]
