"""Visual appearance: colors, typography, and style snippets."""

# Colors
COLOR_DARK_BG = "#0f172a"
COLOR_DARK_WIDGET = "#1e293b"
COLOR_DARK_BORDER = "#334155"
COLOR_DARK_TEXT = "#e2e8f0"
COLOR_DARK_MUTED = "#cbd5e1"
COLOR_DARK_ACCENT = "#0ea5e9"
COLOR_DARK_SUCCESS = "#22c55e"
COLOR_DARK_DANGER = "#ef4444"
COLOR_DARK_SUCCESS_HOVER = "#16a34a"
COLOR_DARK_DANGER_HOVER = "#dc2626"
COLOR_DARK_DANGER_DISABLED = "#7f1d1d"
COLOR_DARK_SUCCESS_DISABLED = "#115e32"
COLOR_DARK_BORDER_STRONG = "#1f2937"

COLOR_LIGHT_BG = "#f8fafc"
COLOR_LIGHT_WIDGET = "#e2e8f0"
COLOR_LIGHT_BORDER = "#cbd5e1"
COLOR_LIGHT_TEXT = "#0f172a"
COLOR_LIGHT_MUTED = "#94a3b8"
COLOR_LIGHT_ACCENT = "#0ea5e9"
COLOR_LIGHT_SUCCESS = "#22c55e"
COLOR_LIGHT_DANGER = "#ef4444"
COLOR_LIGHT_SUCCESS_HOVER = "#16a34a"
COLOR_LIGHT_DANGER_HOVER = "#dc2626"
COLOR_LIGHT_DANGER_DISABLED = "#7f1d1d"
COLOR_LIGHT_SUCCESS_DISABLED = "#115e32"
COLOR_LIGHT_BORDER_STRONG = "#cbd5e1"
COLOR_CARD_TEXT_DARK = COLOR_DARK_TEXT
COLOR_CARD_TEXT_LIGHT = COLOR_LIGHT_TEXT

# Chat-specific colors
COLOR_CHAT_USER_TEXT = "#ffffff"
COLOR_CHAT_ASSISTANT_BORDER_DARK = COLOR_DARK_BORDER
COLOR_CHAT_ASSISTANT_BORDER_LIGHT = COLOR_LIGHT_BORDER_STRONG

# Typography
FONT_FAMILY = "Inter"
FONT_SIZE_TITLE = 14
FONT_SIZE_LABEL = 10
FONT_SIZE_LOG_HEADER = 10
FONT_SIZE_BODY = 11
FONT_WEIGHT_NORMAL = 400
FONT_WEIGHT_SEMIBOLD = 600
FONT_WEIGHT_BOLD = 700

# Style snippets
GUI_CHAT_USER_QSS = (
    "background-color: #0ea5e9; color: white; border-radius: 8px; padding: 8px;"
)
GUI_CHAT_ASSISTANT_QSS = (
    "background-color: #1e293b; color: #e2e8f0; border-radius: 8px; padding: 8px;"
)
GUI_STOP_BUTTON_STYLE = "color: {color}; border: 1px solid {color};"
GUI_STATUS_COLORS = {"ok": "#16a34a", "error": "#ef4444"}

__all__ = [
    "COLOR_DARK_BG",
    "COLOR_DARK_WIDGET",
    "COLOR_DARK_BORDER",
    "COLOR_DARK_TEXT",
    "COLOR_DARK_MUTED",
    "COLOR_DARK_ACCENT",
    "COLOR_DARK_SUCCESS",
    "COLOR_DARK_DANGER",
    "COLOR_DARK_SUCCESS_HOVER",
    "COLOR_DARK_DANGER_HOVER",
    "COLOR_DARK_DANGER_DISABLED",
    "COLOR_DARK_SUCCESS_DISABLED",
    "COLOR_DARK_BORDER_STRONG",
    "COLOR_LIGHT_BG",
    "COLOR_LIGHT_WIDGET",
    "COLOR_LIGHT_BORDER",
    "COLOR_LIGHT_TEXT",
    "COLOR_LIGHT_MUTED",
    "COLOR_LIGHT_ACCENT",
    "COLOR_LIGHT_SUCCESS",
    "COLOR_LIGHT_DANGER",
    "COLOR_LIGHT_SUCCESS_HOVER",
    "COLOR_LIGHT_DANGER_HOVER",
    "COLOR_LIGHT_DANGER_DISABLED",
    "COLOR_LIGHT_SUCCESS_DISABLED",
    "COLOR_LIGHT_BORDER_STRONG",
    "COLOR_CARD_TEXT_DARK",
    "COLOR_CARD_TEXT_LIGHT",
    "COLOR_CHAT_USER_TEXT",
    "COLOR_CHAT_ASSISTANT_BORDER_DARK",
    "COLOR_CHAT_ASSISTANT_BORDER_LIGHT",
    "FONT_FAMILY",
    "FONT_SIZE_TITLE",
    "FONT_SIZE_LABEL",
    "FONT_SIZE_LOG_HEADER",
    "FONT_SIZE_BODY",
    "FONT_WEIGHT_NORMAL",
    "FONT_WEIGHT_SEMIBOLD",
    "FONT_WEIGHT_BOLD",
    "GUI_CHAT_USER_QSS",
    "GUI_CHAT_ASSISTANT_QSS",
    "GUI_STOP_BUTTON_STYLE",
    "GUI_STATUS_COLORS",
]
