"""Environment-sourced configuration (DB, logging, Ollama, paths)."""

import os
from pathlib import Path


def _env_first(names: list[str], default):
    for n in names:
        val = os.getenv(n)
        if val is not None:
            return val
    return default


# Database (env-derived defaults)
DB_HOST = _env_first(
    ["POSTGRES_HOST_RAG", "POSTGRES_HOST", "DB_POSTGRESDB_HOST", "DB_HOST"],
    "localhost",
)
DB_PORT = int(_env_first(["POSTGRES_PORT_RAG", "POSTGRES_PORT", "DB_POSTGRESDB_PORT", "DB_PORT"], "5433"))
DB_NAME = _env_first(["POSTGRES_DB_RAG", "POSTGRES_DB", "DB_POSTGRESDB_DATABASE", "DB_NAME"], "rag")
DB_USER = _env_first(["POSTGRES_USER_RAG", "POSTGRES_USER", "DB_POSTGRESDB_USER", "DB_USER"], "rag")
DB_PASS = _env_first(["POSTGRES_PASSWORD_RAG", "POSTGRES_PASSWORD", "DB_POSTGRESDB_PASSWORD", "DB_PASSWORD"], None)
DB_CONNECT_TIMEOUT = 60
DB_RETRY_MAX_ATTEMPTS = 3
DB_RETRY_BACKOFF = 0.2
# Backward-compatible aliases
DB_DEFAULT_HOST = DB_HOST
DB_DEFAULT_PORT = DB_PORT
DB_DEFAULT_NAME = DB_NAME
DB_DEFAULT_USER = DB_USER
DB_DEFAULT_PASSWORD = DB_PASS
DB_CONNECT_TIMEOUT_SECONDS = DB_CONNECT_TIMEOUT
DB_RETRY_ATTEMPTS = DB_RETRY_MAX_ATTEMPTS
DB_RETRY_BACKOFF_SECONDS = DB_RETRY_BACKOFF

# Logging
LOG_DIR = "logs"
LOG_FILE = "rag.log"
LOG_FMT = "%(asctime)s %(levelname)s [%(name)s] %(message)s"
LOG_LEVEL_DEFAULT = "INFO"
HF_CACHE_PATH: Path = Path.home() / ".cache" / "huggingface"
# Backward-compatible aliases
LOG_DIRECTORY = LOG_DIR
LOG_FILE_NAME = LOG_FILE
LOG_FORMAT = LOG_FMT
DEFAULT_LOG_LEVEL = LOG_LEVEL_DEFAULT
HF_CACHE_DEFAULT_PATH = HF_CACHE_PATH

# Ollama / LLM endpoints
OLLAMA_HOST = "http://127.0.0.1:11434"
OLLAMA_TIMEOUT = 1200.0
OLLAMA_HEALTH_PATH = "/api/tags"
OLLAMA_HEALTH_TIMEOUT = 5.0
OLLAMA_NUM_CTX_DEFAULT = 6000
OLLAMA_STREAM = False
OLLAMA_NUM_PREDICT = "num_predict"
OLLAMA_GENERATE_ENDPOINT = "/api/generate"
# Backward-compatible aliases
OLLAMA_DEFAULT_HOST = OLLAMA_HOST
OLLAMA_HEALTHCHECK_PATH = OLLAMA_HEALTH_PATH
OLLAMA_HEALTH_TIMEOUT_SECONDS = OLLAMA_HEALTH_TIMEOUT
OLLAMA_DEFAULT_NUM_CTX = OLLAMA_NUM_CTX_DEFAULT
OLLAMA_STREAM_FLAG = OLLAMA_STREAM
OLLAMA_NUM_PREDICT_KEY = OLLAMA_NUM_PREDICT
OLLAMA_GENERATE_PATH = OLLAMA_GENERATE_ENDPOINT
OLLAMA_TIMEOUT_SECONDS = OLLAMA_TIMEOUT

# Test / bootstrap
TEST_DB_NAME = "rag_test_db"
INTEGRATION_BOOTSTRAP_ENV = "RUN_SERVICE_BOOTSTRAP"

# Router / chat history tuning
ROUTER_HISTORY_MAX_MESSAGES = 3  # total messages kept (e.g., 3 user/assistant turns)
ROUTER_HISTORY_CHAR_BUDGET = 1200
ROUTER_HISTORY_PER_MESSAGE_TRUNCATE = 200

# Domain extraction / citations
DOMAIN_MAPPING_MAX_TOKENS = 512
DOMAIN_MAPPING_CANDIDATE_LIMIT = 8
CITATION_TOP_K = 2

# Domain extraction / LLM defaults
DOMAIN_MAPPING_MAX_TOKENS = 512
DOMAIN_MAPPING_CANDIDATE_LIMIT = 14

__all__ = [
    "_env_first",
    # DB
    "DB_HOST",
    "DB_PORT",
    "DB_NAME",
    "DB_USER",
    "DB_PASS",
    "DB_CONNECT_TIMEOUT",
    "DB_RETRY_MAX_ATTEMPTS",
    "DB_RETRY_BACKOFF",
    "TEST_DB_NAME",
    "DB_DEFAULT_HOST",
    "DB_DEFAULT_PORT",
    "DB_DEFAULT_NAME",
    "DB_DEFAULT_USER",
    "DB_DEFAULT_PASSWORD",
    "DB_CONNECT_TIMEOUT_SECONDS",
    "DB_RETRY_ATTEMPTS",
    "DB_RETRY_BACKOFF_SECONDS",
    # Logging
    "LOG_DIR",
    "LOG_FILE",
    "LOG_FMT",
    "LOG_LEVEL_DEFAULT",
    "HF_CACHE_PATH",
    # Ollama
    "OLLAMA_HOST",
    "OLLAMA_TIMEOUT",
    "OLLAMA_HEALTH_PATH",
    "OLLAMA_HEALTH_TIMEOUT",
    "OLLAMA_NUM_CTX_DEFAULT",
    "OLLAMA_STREAM",
    "OLLAMA_NUM_PREDICT",
    "OLLAMA_GENERATE_ENDPOINT",
    "OLLAMA_DEFAULT_HOST",
    "OLLAMA_HEALTHCHECK_PATH",
    "OLLAMA_HEALTH_TIMEOUT_SECONDS",
    "OLLAMA_DEFAULT_NUM_CTX",
    "OLLAMA_STREAM_FLAG",
    "OLLAMA_NUM_PREDICT_KEY",
    "OLLAMA_GENERATE_PATH",
    "OLLAMA_TIMEOUT_SECONDS",
    # Bootstrap flag
    "INTEGRATION_BOOTSTRAP_ENV",
    # Backward logging aliases
    "LOG_DIRECTORY",
    "LOG_FILE_NAME",
    "LOG_FORMAT",
    "DEFAULT_LOG_LEVEL",
    "HF_CACHE_DEFAULT_PATH",
    # Router history tuning
    "ROUTER_HISTORY_MAX_MESSAGES",
    "ROUTER_HISTORY_CHAR_BUDGET",
    "ROUTER_HISTORY_PER_MESSAGE_TRUNCATE",
    # Domain extraction
    "DOMAIN_MAPPING_MAX_TOKENS",
    "DOMAIN_MAPPING_CANDIDATE_LIMIT",
    # Citations
    "CITATION_TOP_K",
]
